FROM node:12.14.1
WORKDIR /home/node/app/frontend/
COPY package*.json ./
RUN npm install
COPY . .
WORKDIR /home/node/app/frontend/src/

# production environment
FROM nginx:1.17.7
COPY --from=build /home/node/app/frontend/build /home/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]